# Site settings
title: aria lulu
baseurl: #""
url: "http://www.chenglinglu.com"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave blank to disable it
google_analytics: 
disqus_shortname: 
